name: "C# Development Workflow"
version: "1.0"
description: "Complete C# development workflow with architecture review, TDD, and quality gates"

steps:
  - id: "requirements"
    name: "Requirements Analysis"
    description: "Analyze and document requirements"
    agent: "requirements-engineer"
    inputs: []
    outputs: ["requirements_doc"]
    transitions:
      - to: "specification"

  - id: "specification"
    name: "Technical Specification"
    description: "Create detailed technical specifications"
    agent: "spec-author"
    inputs: ["requirements_doc"]
    outputs: ["tech_spec", "api_contracts"]
    approvals:
      - agent: "product-manager"
        condition: "requirements_met"
    transitions:
      - to: "architecture"

  - id: "architecture"
    name: "Architecture Design"
    description: "Design system architecture following C# best practices and SOLID principles"
    agent: "architect"
    inputs: ["tech_spec"]
    outputs: ["architecture_doc", "design_patterns"]
    approvals:
      - agent: "engineering-manager"
        condition: "architecture_approved"
    transitions:
      - to: "implementation"

  - id: "implementation"
    name: "TDD Implementation"
    description: "Implement features using Test-Driven Development"
    agent: "programmer"
    inputs: ["tech_spec", "architecture_doc"]
    outputs: ["source_code", "unit_tests"]
    transitions:
      - to: "standards-audit"

  - id: "standards-audit"
    name: "Coding Standards Audit"
    description: "Verify code follows C# coding standards and conventions"
    agent: "coding-standards-auditor"
    inputs: ["source_code"]
    outputs: ["audit_report"]
    approvals:
      - agent: "coding-standards-auditor"
        condition: "standards_pass"
    transitions:
      - to: "qa-testing"
        condition: "pass"
      - to: "implementation"
        condition: "fail"

  - id: "qa-testing"
    name: "QA Testing & Validation"
    description: "Execute test plan and validate quality"
    agent: "qa-engineer"
    inputs: ["source_code", "unit_tests", "tech_spec"]
    outputs: ["test_results", "qa_report"]
    approvals:
      - agent: "qa-engineer"
        condition: "tests_pass"
    transitions:
      - to: "policy-gate"
        condition: "pass"
      - to: "implementation"
        condition: "fail"

  - id: "policy-gate"
    name: "Policy & Security Gate"
    description: "Verify compliance with security and organizational policies"
    agent: "policy-gate"
    inputs: ["source_code", "architecture_doc", "qa_report"]
    outputs: ["compliance_report"]
    approvals:
      - agent: "policy-gate"
        condition: "policies_met"
    transitions:
      - to: "final-review"
        condition: "pass"
      - to: "implementation"
        condition: "security_fail"
      - to: "architecture"
        condition: "architecture_fail"

  - id: "final-review"
    name: "Engineering Manager Review"
    description: "Final code review and approval for deployment"
    agent: "engineering-manager"
    inputs: ["source_code", "test_results", "compliance_report"]
    outputs: ["approval"]
    approvals:
      - agent: "engineering-manager"
        condition: "approved"
    transitions:
      - to: "complete"

  - id: "complete"
    name: "Complete"
    description: "Work is approved and ready for deployment"
    agent: "sdlc-orchestrator"
    inputs: ["approval"]
    outputs: ["deployment_ready"]

metadata:
  stack: "csharp"
  framework: ".NET 8"
  testing_framework: "xUnit/NUnit"
  principles:
    - "Test-Driven Development (TDD)"
    - "SOLID Principles"
    - "Clean Architecture"
    - "Dependency Injection"
  conventions:
    - "PascalCase for classes and methods"
    - "camelCase for local variables"
    - "Async/await for I/O operations"
    - "XML documentation comments"
